const shoppingStoresData = [
    {
      id: "target",
      name: "Target",
      logo_url: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Target_logo.svg",
      mode: "fast",
      delays: { monitor: 1500, retry: 1000, checkout: 500 },
      supported_regions: ["US"],
      uses_account: false,
      uses_proxy: true,
      uses_captcha: false,
      base_url: "https://www.target.com",
      search_url_template: "https://www.target.com/s?searchTerm={keyword}",
      product_url_pattern: "/A-(\\d{8})",
      supports_variant_add_to_cart: true,
      requires_size_selection: true,
      queue_supported: false,
      browser_required_for_checkout: false,
      checkout_type: "standard",
      uses_virtual_card_recommendation: true,
      anti_bot_notes: "May return outdated stock info via RedSky API. Use browser fallback if critical."
    },
    {
      id: "nike",
      name: "Nike",
      logo_url: "https://1000logos.net/wp-content/uploads/2017/03/Nike-Logo.png",
      mode: "browser",
      delays: { monitor: 3000, retry: 2000, checkout: 1000 },
      supported_regions: ["US", "EU", "CA"],
      uses_account: true,
      uses_proxy: true,
      uses_captcha: true,
      base_url: "https://www.nike.com",
      search_url_template: "https://www.nike.com/w?q={keyword}",
      product_url_pattern: "/t/.*?/(\\d+)",
      supports_variant_add_to_cart: true,
      requires_size_selection: true,
      queue_supported: true,
      browser_required_for_checkout: true,
      checkout_type: "standard",
      uses_virtual_card_recommendation: false,
      anti_bot_notes: "Uses Akamai bot protection, heavy fingerprinting."
    },
    {
      id: "supreme",
      name: "Supreme",
      logo_url: "https://1000logos.net/wp-content/uploads/2020/09/Supreme-Logo.png",
      mode: "fast",
      delays: { monitor: 1000, retry: 750, checkout: 500 },
      supported_regions: ["US", "EU", "JP"],
      uses_account: false,
      uses_proxy: true,
      uses_captcha: true,
      base_url: "https://www.supremenewyork.com",
      search_url_template: "https://www.supremenewyork.com/shop/search?q={keyword}",
      product_url_pattern: "/shop/(\\d+)",
      supports_variant_add_to_cart: true,
      requires_size_selection: true,
      queue_supported: true,
      browser_required_for_checkout: false,
      checkout_type: "standard",
      uses_virtual_card_recommendation: true,
      anti_bot_notes: "Bot detection during checkout; rotate proxies and use safe delays."
    },
    {
      id: "walmart",
      name: "Walmart",
      logo_url: "https://1000logos.net/wp-content/uploads/2017/06/Walmart-Logo.png",
      mode: "fast",
      delays: { monitor: 2000, retry: 1500, checkout: 800 },
      supported_regions: ["US"],
      uses_account: true,
      uses_proxy: true,
      uses_captcha: false,
      base_url: "https://www.walmart.com",
      search_url_template: "https://www.walmart.com/search?q={keyword}",
      product_url_pattern: "/ip/(\\d+)",
      supports_variant_add_to_cart: true,
      requires_size_selection: false,
      queue_supported: false,
      browser_required_for_checkout: false,
      checkout_type: "standard",
      uses_virtual_card_recommendation: false,
      anti_bot_notes: "Bot detection varies. Better results on browser emulation."
    },
    {
      id: "footlocker",
      name: "Foot Locker",
      logo_url: "https://seeklogo.com/images/F/foot-locker-logo-8174E67888-seeklogo.com.png",
      mode: "fast",
      delays: { monitor: 1500, retry: 1200, checkout: 600 },
      supported_regions: ["US", "EU", "CA"],
      uses_account: false,
      uses_proxy: true,
      uses_captcha: true,
      base_url: "https://www.footlocker.com",
      search_url_template: "https://www.footlocker.com/search?q={keyword}",
      product_url_pattern: "/product/(\\d+)",
      supports_variant_add_to_cart: true,
      requires_size_selection: true,
      queue_supported: true,
      browser_required_for_checkout: false,
      checkout_type: "standard",
      uses_virtual_card_recommendation: true,
      anti_bot_notes: "QITM queue detection recommended for drop times."
    },
    {
      id: "bestbuy",
      name: "Best Buy",
      logo_url: "https://upload.wikimedia.org/wikipedia/commons/2/29/Best_Buy_Logo.svg",
      mode: "fast",
      delays: { monitor: 2500, retry: 2000, checkout: 900 },
      supported_regions: ["US", "CA"],
      uses_account: true,
      uses_proxy: true,
      uses_captcha: false,
      base_url: "https://www.bestbuy.com",
      search_url_template: "https://www.bestbuy.com/site/searchpage.jsp?st={keyword}",
      product_url_pattern: "/site/.*?/([0-9]{7})\\.p",
      supports_variant_add_to_cart: false,
      requires_size_selection: false,
      queue_supported: false,
      browser_required_for_checkout: false,
      checkout_type: "standard",
      uses_virtual_card_recommendation: false,
      anti_bot_notes: "Frequent changes in API endpoints."
    },
    {
      id: "shopify",
      name: "Shopify",
      logo_url: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Shopify_logo_2018.svg",
      mode: "fast",
      delays: { monitor: 1000, retry: 750, checkout: 300 },
      supported_regions: ["US", "EU"],
      uses_account: false,
      uses_proxy: true,
      uses_captcha: true,
      base_url: "https://shop.app",
      search_url_template: "",
      product_url_pattern: "/products/(.*)",
      supports_variant_add_to_cart: true,
      requires_size_selection: true,
      queue_supported: false,
      browser_required_for_checkout: false,
      checkout_type: "shopPay",
      uses_virtual_card_recommendation: true,
      anti_bot_notes: "Bot protection is store-dependent. Use safe delays."
    },
    {
      id: "snkrs",
      name: "SNKRS",
      logo_url: "https://1000logos.net/wp-content/uploads/2021/05/Nike-SNKRS-logo.png",
      mode: "browser",
      delays: { monitor: 5000, retry: 3000, checkout: 1500 },
      supported_regions: ["US", "EU"],
      uses_account: true,
      uses_proxy: true,
      uses_captcha: true,
      base_url: "https://www.nike.com/launch",
      search_url_template: "",
      product_url_pattern: "/launch/t/.*/(\\d+)",
      supports_variant_add_to_cart: false,
      requires_size_selection: true,
      queue_supported: true,
      browser_required_for_checkout: true,
      checkout_type: "standard",
      uses_virtual_card_recommendation: false,
      anti_bot_notes: "Uses draw and raffle methods. Headless checkout not supported."
    },
    {
        id: "amazon",
        name: "Amazon",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
        mode: "safe",
        delays: { monitor: 3500, retry: 2500, checkout: 1000 },
        supported_regions: ["US", "EU", "CA", "IN", "JP"],
        uses_account: true,
        uses_proxy: true,
        uses_captcha: true,
        base_url: "https://www.amazon.com",
        search_url_template: "https://www.amazon.com/s?k={keyword}",
        product_url_pattern: "/dp/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: false,
        browser_required_for_checkout: true,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Uses heavy bot detection and dynamic content rendering."
      },
      {
        id: "costco",
        name: "Costco",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/5/58/Costco_Wholesale_logo_2010-10-26.svg",
        mode: "safe",
        delays: { monitor: 3000, retry: 2000, checkout: 1000 },
        supported_regions: ["US"],
        uses_account: true,
        uses_proxy: false,
        uses_captcha: false,
        base_url: "https://www.costco.com",
        search_url_template: "https://www.costco.com/CatalogSearch?dept=All&keyword={keyword}",
        product_url_pattern: "/product/(\\w+)",
        supports_variant_add_to_cart: false,
        requires_size_selection: false,
        queue_supported: false,
        browser_required_for_checkout: false,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Requires membership; limited stock updates."
      },
      {
        id: "gamestop",
        name: "GameStop",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/2/2f/GameStop_logo.svg",
        mode: "fast",
        delays: { monitor: 1500, retry: 1000, checkout: 600 },
        supported_regions: ["US"],
        uses_account: true,
        uses_proxy: true,
        uses_captcha: false,
        base_url: "https://www.gamestop.com",
        search_url_template: "https://www.gamestop.com/search/?q={keyword}",
        product_url_pattern: "/product/(\\d+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: false,
        queue_supported: false,
        browser_required_for_checkout: false,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Use safe delays and rotate proxies."
      },
      {
        id: "kith",
        name: "Kith",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/1/14/Kith-logo.png",
        mode: "fast",
        delays: { monitor: 1200, retry: 900, checkout: 400 },
        supported_regions: ["US", "EU"],
        uses_account: false,
        uses_proxy: true,
        uses_captcha: true,
        base_url: "https://kith.com",
        search_url_template: "https://kith.com/search?q={keyword}",
        product_url_pattern: "/products/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: false,
        browser_required_for_checkout: false,
        checkout_type: "shopPay",
        uses_virtual_card_recommendation: true,
        anti_bot_notes: "Uses Shopify backend. Expect anti-bot measures during drops."
      },
      {
        id: "adidas",
        name: "Adidas",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg",
        mode: "safe",
        delays: { monitor: 3000, retry: 2000, checkout: 1000 },
        supported_regions: ["US", "EU", "CA"],
        uses_account: true,
        uses_proxy: true,
        uses_captcha: true,
        base_url: "https://www.adidas.com",
        search_url_template: "https://www.adidas.com/us/search?q={keyword}",
        product_url_pattern: "/product/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: true,
        browser_required_for_checkout: true,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Bot protection includes waiting rooms and CAPTCHA walls."
      },
      {
        id: "yeezysupply",
        name: "Yeezy Supply",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/f/fd/Yeezy_logo.png",
        mode: "browser",
        delays: { monitor: 5000, retry: 4000, checkout: 2000 },
        supported_regions: ["US"],
        uses_account: false,
        uses_proxy: true,
        uses_captcha: true,
        base_url: "https://www.yeezysupply.com",
        search_url_template: "",
        product_url_pattern: "/product/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: true,
        browser_required_for_checkout: true,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Uses waiting room and bot-detection on Cloudflare."
      },
      {
        id: "bape",
        name: "BAPE",
        logo_url: "https://upload.wikimedia.org/wikipedia/en/5/58/Bape_logo.svg",
        mode: "fast",
        delays: { monitor: 1500, retry: 1200, checkout: 500 },
        supported_regions: ["JP", "US"],
        uses_account: false,
        uses_proxy: true,
        uses_captcha: true,
        base_url: "https://us.bape.com",
        search_url_template: "https://us.bape.com/search?q={keyword}",
        product_url_pattern: "/products/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: false,
        browser_required_for_checkout: false,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Limited drops. Shopify-based. Easy to get blocked."
      },
      {
        id: "newbalance",
        name: "New Balance",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/5/5e/New_Balance_logo.svg",
        mode: "safe",
        delays: { monitor: 2000, retry: 1500, checkout: 700 },
        supported_regions: ["US", "EU"],
        uses_account: true,
        uses_proxy: true,
        uses_captcha: false,
        base_url: "https://www.newbalance.com",
        search_url_template: "https://www.newbalance.com/search?q={keyword}",
        product_url_pattern: "/product/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: false,
        browser_required_for_checkout: false,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Mild anti-bot. Better results with size variant lookup."
      },
      {
        id: "undefeated",
        name: "Undefeated",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/8/83/Undefeated_Logo.png",
        mode: "fast",
        delays: { monitor: 1000, retry: 800, checkout: 400 },
        supported_regions: ["US"],
        uses_account: false,
        uses_proxy: true,
        uses_captcha: true,
        base_url: "https://undefeated.com",
        search_url_template: "https://undefeated.com/search?q={keyword}",
        product_url_pattern: "/products/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: false,
        browser_required_for_checkout: false,
        checkout_type: "shopPay",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Uses Shopify. Drops protected with CAPTCHA and queues."
      },
      {
        id: "dicks",
        name: "Dick's Sporting Goods",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Dicks_Sporting_Goods_logo.svg",
        mode: "fast",
        delays: { monitor: 1800, retry: 1400, checkout: 600 },
        supported_regions: ["US"],
        uses_account: true,
        uses_proxy: true,
        uses_captcha: true,
        base_url: "https://www.dickssportinggoods.com",
        search_url_template: "https://www.dickssportinggoods.com/search/SearchDisplay?searchTerm={keyword}",
        product_url_pattern: "/p/.*/(\\d+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: false,
        browser_required_for_checkout: false,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Track cart API changes; rotates security headers frequently."
      },
      {
        id: "hibbett",
        name: "Hibbett Sports",
        logo_url: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c1/Hibbett_Sports_logo.svg/1200px-Hibbett_Sports_logo.svg.png",
        mode: "fast",
        delays: { monitor: 1600, retry: 1300, checkout: 500 },
        supported_regions: ["US"],
        uses_account: true,
        uses_proxy: true,
        uses_captcha: false,
        base_url: "https://www.hibbett.com",
        search_url_template: "https://www.hibbett.com/search/?q={keyword}",
        product_url_pattern: "/product/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: false,
        browser_required_for_checkout: false,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "API can reject requests if headers aren't correct."
      },
      {
        id: "jd",
        name: "JD Sports",
        logo_url: "https://upload.wikimedia.org/wikipedia/commons/4/4f/JD_Sports_logo.svg",
        mode: "safe",
        delays: { monitor: 2000, retry: 1500, checkout: 700 },
        supported_regions: ["US", "EU"],
        uses_account: true,
        uses_proxy: true,
        uses_captcha: true,
        base_url: "https://www.jdsports.com",
        search_url_template: "https://www.jdsports.com/search?q={keyword}",
        product_url_pattern: "/product/(\\w+)",
        supports_variant_add_to_cart: true,
        requires_size_selection: true,
        queue_supported: true,
        browser_required_for_checkout: false,
        checkout_type: "standard",
        uses_virtual_card_recommendation: false,
        anti_bot_notes: "Session-based drops with queue. Prepare early."
      }
      
  ];
  

  module.exports.shoppingStoresData = shoppingStoresData;
